In [4]:
##Find arithmetic mean of 20, 2, 7, 1, 34 
import numpy as np
import statistics as stats
import scipy as sp

In [5]:
A=[20,2,7,1,34]
B=np.mean(A)
print(B)

12.8


In [7]:
A=[[14,17,12,33,44],[15,6,27,8,19],[23,2,54,1,4]]
B=np.mean(A)
C=np.mean(A, axis=0)
D=np.mean(A, axis=1)
print(B)
print(C)
print(D)

18.6
[17.33333333  8.33333333 31.         14.         22.33333333]
[24.  15.  16.8]


In [9]:
A=[[3,7,5],[8,4,3],[2,4,9]]
B=np.max(A)
C=np.min(A)
D=np.max(A,axis=0)
E=np.min(A,axis=0)
F=np.max(A,axis=1)
G=np.min(A,axis=1)
Range1 = np.ptp(A)
Range2 = np.ptp(A, axis=0)
Range3 = np.ptp(A, axis=1)
print(B)
print(C)
print(D)
print(E)
print(F)
print(G)
print(Range1)
print(Range2)
print(Range3)

9
2
[8 7 9]
[2 4 3]
[7 8 9]
[3 3 2]
7
[6 3 6]
[4 5 7]
