In [4]:
##Find arithmetic mean of 20, 2, 7, 1, 34 
import numpy as np
import statistics as stats
import scipy as sp

In [5]:
A=[20,2,7,1,34]
B=np.mean(A)
print(B)

12.8


In [11]:
A=[[14,17,12,33,44],[15,6,27,8,19],[23,2,54,1,4]]
B=np.mean(A)
C=np.mean(A, axis=0)
D=np.mean(A, axis=1)
print(B)
print(C)
print(D)

18.6
[17.33333333  8.33333333 31.         14.         22.33333333]
[24.  15.  16.8]


In [9]:
A=[[3,7,5],[8,4,3],[2,4,9]]
B=np.max(A)
C=np.min(A)
D=np.max(A,axis=0)
E=np.min(A,axis=0)
F=np.max(A,axis=1)
G=np.min(A,axis=1)
Range1 = np.ptp(A)
Range2 = np.ptp(A, axis=0)
Range3 = np.ptp(A, axis=1)
print(B)
print(C)
print(D)
print(E)
print(F)
print(G)
print(Range1)
print(Range2)
print(Range3)

9
2
[8 7 9]
[2 4 3]
[7 8 9]
[3 3 2]
7
[6 3 6]
[4 5 7]


In [13]:
A=[1,2,3,4]
W=[4,3,2,1]
Answer=np.average(A,weights=W)
print(Answer)

2.0


In [14]:
Speed=[99,86,87,88,111,86,103,87,94,78,77,85,86]
Mean=np.mean(Speed)
Median=np.median(Speed)
Mode=stats.mode(Speed)
print(Mean)
print(Median)
print(Mode)

89.76923076923077
87.0
86


In [21]:
A=np.array([[ 1,  3, 27],
       [ 3,  4,  6],
       [ 7,  6,  3],
       [ 3,  6,  8]])
from scipy.stats import gmean
B=gmean(gmean(A))
C=gmean(A,axis=0)
D=gmean(A,axis=1)
print(B)
print(C)
print(D)

4.663506066439651
[2.81731325 4.55901411 7.89644408]
[4.32674871 4.16016765 5.01329793 5.24148279]


In [22]:
A=[1, 3, 5, 7, 9]
H=stats.harmonic_mean(A)
print(H)

2.797513321492007


In [25]:
A=[30,40,72,83,25,10,50,90,60,15,5,9,34,23,67,80,67,45]
print(np.percentile(A,30))
print(np.percentile(A,50))
print(np.percentile(A,75))
print(np.percentile(A,90))

25.5
42.5
67.0
80.9


In [26]:
A=[51, 38, 79, 46, 57]
print(stats.stdev(A))
print(np.std(A))

15.514509338035799
13.876599006961325


In [28]:
W = [6.3, 7.2, 7.3, 8.1, 7.8, 6.8, 7.5, 7.8, 7.2, 7.5, 8.1, 8.2 , 8.0, 7.4, 7.6, 7.7, 7.6, 7.4, 7.5, 8.4, 7.4, 7.6, 6.2, 7.4]
O=np.std(W)
OW=stats.stdev(W)
OWO=np.average(W)
print(O)
print(OW)
print(OWO)
print("Not Accepted")

0.5163977794943222
0.5275043787166296
7.5
Not Accepted


In [29]:
avg1 = 32.11
var1 = 68.09
sd1 = var1**0.5
rv1 = (sd1/avg1)*100
avg2 = 19.75
var2 = 71.14
sd2 = var2**0.5
rv2 = (sd2/avg2)*100
print("Coefficient of variation of both programs are %f and %f respectively."%(rv1,rv2))
if (rv1<rv2):
    print("Training program A has lesser variability than variableB.")
else:
    print("Training program B has lesser variability than variableA.")

Coefficient of variation of both programs are 25.698121 and 42.706092 respectively.
Training program A has lesser variability than variableB.
